INSERT INTO burgers (burgername, devoured) VALUES ("Foot Feta-ish Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Mission A-Corn-Plished Burger (comes with corn salsa)", false);
INSERT INTO burgers (burgername, devoured) VALUES ("These Collards Don't Run Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Last of the Mo-Jicama Burger (comes with jicama)", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Olive and Let Die Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Thank God it's Fried Egg Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Camembert-ly Legal Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Poblano Picasso Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Salvador Cauliflower Burger", false);
INSERT INTO burgers (burgername, devoured) VALUES ("Hit Me with Your Best Shallot Burger", false);